name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout repository
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build docker
        env:
          PROJECT_ID: kultz-ch
          GCLOUD_AUTH: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KULTZ }}
        run: |
          yarn install
          yarn build
          # https://cloud.google.com/container-registry/docs/advanced-authentication
          printenv GCLOUD_AUTH | base64 --decode | docker login -u _json_key --password-stdin https://eu.gcr.io
          docker build --pull -t eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/api:${GITHUB_SHA} ./api
          docker push eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/api:${GITHUB_SHA}
          docker build --pull -t eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/editor:${GITHUB_SHA} ./editor
          docker push eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/editor:${GITHUB_SHA}
          docker build --pull -t eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/media:${GITHUB_SHA} ./media
          docker push eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/media:${GITHUB_SHA}
          docker build --pull -t eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/website:${GITHUB_SHA} ./website
          docker push eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/website:${GITHUB_SHA}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Create manifest
        env:
          PROJECT_ID: wepublish-269314
        run: |
          node ./create-gke-manifest.js
          ls -al ./kubernetesConfigs
      - name: Prepare and authenticate kubectl
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: tsri-django
          location: europe-west6-c
          project_id: tsri-246213
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_TSRI }}
      - name: Deploy to kubernetes
        run: kubectl apply -f ./kubernetesConfigs
